title: The Gin - Human Interactive AI Card Game
description: Group Activity Blog
author: "Kanglin Xu"

theme: minima

base_url: /web_page
repository: TheGinAI/web_page

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/schedule.md

include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
    - README.md
