theme: minima
title: The Gin's Web Page
author: Kanglin Xu
description: This web page will contain information about group member and their roles, group meeting and activities, upcoming schedules and etc... 
